seed: 0
exp_name: single_model

device:
  cuda_device: cuda:6
  gpu_num_workers: 16

data:
  img_dir: ../data/AI against COVID-19/COVIDX
  fold_dir: ../data/AI against COVID-19
  box_file: ./data/processed/data.xlsx
  model_dir: ./models/cnn
  report_dir: ./reports
  classes:
    - negative
    - positive
  img_dim: 224
  batch_size: 32

model:
  model_list:
    - vgg11_bn
    - vgg13_bn
    - vgg16_bn
    - vgg19_bn
    - resnet18
    - resnet34
    - resnet50
    - resnet101
    - resnet152
    - resnext50_32x4d
    - resnext101_32x8d
    - wide_resnet50_2
    - wide_resnet101_2
    - squeezenet1_1
    - densenet121
    - densenet169
    - densenet161
    - densenet201
    - googlenet
    - shufflenet_v2_x0_5
    - shufflenet_v2_x1_0
    - shufflenet_v2_x1_5
    - shufflenet_v2_x2_0
    - mobilenet_v2
    - mnasnet0_5
    - mnasnet1_0
  feature_extract: False
  pretrained: True


trainer:
  optimizer:
    lr: 0.001
  scheduler:
      mode: min
      patience: 5
  early_stopping: 25
  max_epochs: 300

features:
  feature_dir: ./data/interim/features